b_thresh: 6.0  # brightness threshold, recommend 5-6 to start with
cam_config_file: ""  # the name of the camera config file located in data directory
save_directory: ""  # Directory to save the catalog to.