b_thresh: 6.0  # brightness threshold, recommend 5-6 to start with
cam_config_file: "/home/jhand/projects/kef_celestialnav/celestialnav/cameras/config/allcams/imx2.yaml"  # the name of the camera config file located in data directory
save_directory: "/home/jhand/projects/kef_COTS-Star-Tracker/data"  # Directory to save the catalog to.
starcat_file: "/home/jhand/projects/kef_COTS-Star-Tracker/data/starcat.tsv"